[package]
name = "aoc2023-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc2023_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits", "parsing"] }
quote = "*"
proc-macro2 = "*"
